#cloud-config
package_update: true
package_upgrade: true

runcmd:
  - apt install git ansible docker.io -y
  - git clone https://github.com/intel/optimized-cloud-recipes.git /opt/optimized-cloud-recipes
  - cd /opt/optimized-cloud-recipes
  - git checkout wsfowler-gaudi
  - echo "@reboot ansible-playbook /opt/optimized-cloud-recipes/recipes/ai-gaudi-ubuntu/recipe.yml" | crontab - 
  - reboot


# Run the Ansible playbook from https://github.com/intel/optimized-cloud-recipes/tree/main/recipes/ai-gaudi-ubuntu/recipe.yml
# Path: recipe.yml
# ansible:
#   install_method: distro
#   package_name: ansible
#   pull:
#     url: "https://github.com/intel/optimized-cloud-recipes"
#     playbook_name: "recipes/ai-gaudi-ubuntu/recipe.yml"
#     checkout: wsfowler-gaudi
